---
services:
  minecraft_survival_prod:
    container_name: minecraft_survival_prod
    image: ghcr.io/shepherdjerred-minecraft/paper:1.20
    tty: true
    stdin_open: true
    volumes:
      - /home/ubuntu/servers/survival/prod:/home/minecraft/server:z
    ports:
      - 25565:25565/tcp
      - 25565:25565/udp
    command: -Xmx8G -Dlog4j.configurationFile=log4j2.xml -jar "../paper.jar"
    restart: unless-stopped
  minecraft_creative_prod:
    container_name: minecraft_creative_prod
    image: ghcr.io/shepherdjerred-minecraft/paper:1.20
    tty: true
    stdin_open: true
    volumes:
      - /home/ubuntu/servers/creative/prod:/home/minecraft/server:z
    ports:
      - 25566:25565/tcp
      - 25566:25565/udp
    command: -Xmx1G -jar "../paper.jar"
    restart: unless-stopped
