name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      skip_beta:
        description: "Skip deploying to beta"
        type: boolean
        required: false
        default: false
      ref:
        description: "The ref to deploy"
        required: true
        default: "main"

jobs:
  docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
    environment:
      name: docs
      url: https://docs.ts-mc.net/
    steps:
      - uses: earthly/actions-setup@v1.0.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: deploy
        run: earthly --push --ci --sat monorepo --org the-storm -P ./docs+deploy
  site:
    name: Deploy Site
    runs-on: ubuntu-latest
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
    environment:
      name: site
      url: https://ts-mc.net/
    steps:
      - uses: earthly/actions-setup@v1.0.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: deploy
        run: earthly --push --ci --sat monorepo --org the-storm -P ./site+deploy
  infra:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
    steps:
      - uses: earthly/actions-setup@v1.0.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: deploy
        run: earthly --push --ci --sat monorepo --org the-storm -P ./server+deploy --stage=infra
  beta:
    name: Deploy to Beta
    runs-on: ubuntu-latest
    if: ${{ !github.event.inputs.skip_beta }}
    needs:
      - infra
    environment:
      name: beta
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
    steps:
      - uses: earthly/actions-setup@v1.0.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: deploy
        run: earthly --push --ci --sat monorepo --org the-storm -P ./server+deploy --stage=beta
  prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: ${{ always() && !failure() }}
    needs:
      - beta
    environment:
      name: prod
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
    steps:
      - uses: earthly/actions-setup@v1.0.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: deploy
        run: earthly --push --ci --sat monorepo --org the-storm -P ./server+deploy --stage=prod
